version: 1.0.{build}

branches:
  only:
  - master

image: Visual Studio 2015

init:
- ps: git config --global core.autocrlf True

build_script:
- ps: .\build PublishNuget

environment:
    COVERALLS_REPO_TOKEN:
        secure: BwQmNyV7DWMyQ19aCRlXJRgGEZ8c8lg9YBvW2bGwIzZIsXFBHUDgTJ+QNIzYBC51
    NUGET_API_KEY:
        secure: MqSFQzGO7KDM7kx7rJKnnro90VF4RWUb9TnApOdIqBw86+/YgpqC9rQWzzczL9q0

test: off
