version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
init:
- ps: git config --global core.autocrlf True
build_script:
- ps: .\build BuildAndRunAllTests
test: off
environment:
	COVERALLS_REPO_TOKEN:
		secure: BwQmNyV7DWMyQ19aCRlXJRgGEZ8c8lg9YBvW2bGwIzZIsXFBHUDgTJ+QNIzYBC51
